
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:http: http://localhost:9761/eureka

server:
  port: 8095
spring:
  application:
    name: subscription
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:subscription
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect